version: '3'
services:

  nginx:
    container_name: ux-symfony-nginx
    depends_on:
      - php
    image: nginx:1.17
    environment:
      PHP_EXTENSION_DEBUG: 1
      PHP_INI_XDEBUG_REMOTE: 9001
      PHP_IDE_CONFIG: "docker.ux-symfony.trustedshops.com"
      XDEBUG_CONFIG: "remote_port=9004 remote autostart=1"
    ports:
      - "8100:80"
    volumes:
      - .:/home/wwwroot/project:delegated
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    working_dir: /home/wwwroot/project
    networks:
      - ts-ux-symfony-network

  php:
    build: docker/php
    container_name: ux-symfony-php
    environment:
      XDEBUG_CONFIG: >-
        client_host=host.docker.internal
      XDEBUG_MODE: debug
      PHP_IDE_CONFIG: serverName=Docker-Server
      SERVICE_NAME: ux-symfony
      SERVICE_TAGS: dev
    volumes:
      - .:/home/wwwroot/project:delegated
    networks:
      - ts-ux-symfony-network
    depends_on:
      - sqlite

  sqlite:
    image: nouchka/sqlite3:latest
    container_name: ux-symfony-sqlite
    stdin_open: true
    tty: true
    volumes:
      - ./docker/db/:/root/db/
    networks:
      - ts-ux-symfony-network

networks:
  ts-ux-symfony-network:
    driver: bridge
